docs_dir: content
extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/dgnsrekt
    name: dgnsrekt on twitter
  - icon: fontawesome/brands/github
    link: https://github.com/dgnsrekt
    name: dgnsrekt on twitter
  - icon: fontawesome/brands/telegram
    link: https://t.me/dgnsrekt
    name: dgnsrekt on twitter
  - icon: fontawesome/solid/paper-plane
    link: mailto:dgnsrekt@pm.me
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- admonition
- attr_list
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.details
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.betterem:
    smart_enable: all
nav:
- Overview: index.md
- Quickstart: quickstart.md
- Examples:
  - Basics: examples/basics.md
  - Extras: examples/extras.md
- API Documentation:
  - Balancer Module: api/balancer-module.md
  - Circuit Module: api/circuit-module.md
  - Client Module: api/client-module.md
  - Core Module: api/core-module.md
  - Mount Module: api/mount-module.md
  - Network Module: api/network-module.md
  - Paths Module: api/paths-module.md
repo_url: https://github.com/dgnsrekt/requests-whaor
site_name: requests_whaor
theme:
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  palette:
    accent: red
    primary: red
    scheme: slate
